services:
  api:
    build:
      context: .
      dockerfile: "Dockerfile"
    container_name: api
    environment:
      PORT: 8000
    ports:
      - '8000:8000'
    restart: "no"

# Future work, unrequired at the moment
#  db:
#    image: postgres
#    restart: always
#    environment:
#      POSTGRES_PASSWORD: example
#
#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - "8080:8080"
