services:
  api:
    build:
      context: .
      dockerfile: "Dockerfile"
    container_name: api
    environment:
      PORT: 8000
    ports:
      - '8000:8000'
    restart: "no"
    links:
      - "db:database"

  db:
    image: postgres
    restart: always
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - ./db-data/:/var/lib/postgresql/data/

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
