services:
  db:
    image: postgres
    container_name: "hard-brain-api-test-db"
    environment:
      PGUSER: "postgres"
      POSTGRES_DB: "hard-brain-db"
      DB_HOSTNAME: "db"
      POSTGRES_PASSWORD: "testdb"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/

volumes:
  pgdata:
