services:
  server:
    build:
      context: .
      dockerfile: "Dockerfile"
    container_name: api
    environment:
      PORT: 8000
    env_file:
      - ./.env
    ports:
      - '8000:8000'
    restart: always
    depends_on:
      db:
        condition: service_healthy
    links:
      - "db:database"

  db:
    image: postgres
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  pgdata:
