services:
  server:
    build:
      context: .
      dockerfile: "Dockerfile"
    environment:
      PORT: 8000
      PGUSER: "postgres"
      POSTGRES_DB: "hard-brain-db"
      DB_HOSTNAME: "db"
      POSTGRES_PASSWORD: "<your password here>"
    ports:
      - '8000:8000'
    restart: always
    depends_on:
      db:
        condition: service_healthy
    links:
      - "db:database"

  db:
    image: postgres
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 2s
      timeout: 10s
      retries: 10
    environment:
      PGUSER: "postgres"
      POSTGRES_DB: "hard-brain-db"
      DB_HOSTNAME: "db"
      POSTGRES_PASSWORD: "<your password here>"
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  pgdata:
